version: '3.1'

services:

  api:
    container_name: my-garden-api
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    expose: 80
    environment:
      API_PORT: 80
      MONGODB_HOST: mongo,27017
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: mypassword

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword
      ME_CONFIG_MONGODB_URL: mongodb://root:mypassword@mongo:27017/
      ME_CONFIG_BASICAUTH: false